function laShareResult(){const monthly=document.getElementById('la-monthly').textContent.trim();const interest=document.getElementById('la-total-interest').textContent.trim();const total=document.getElementById('la-total-cost').textContent.trim();const date=document.getElementById('la-payoff-date').textContent.trim();let text='My Loan Amortization Summary (via DebtFreePathways.com)\n';text+='━━━━━━━━━━━━━━━━━━━━━━━━\n';text+='💳 Monthly payment: '+monthly+'\n';text+='💸 Total interest: '+interest+'\n';text+='💰 Total cost: '+total+'\n';text+='📅 Payoff date: '+date+'\n';text+='\nShare this result: '+window.location.href;copyResult(text,'la-share-btn');}

function daShareResult(){const title=document.getElementById('da-savings-title').textContent.trim();const avMonths=document.getElementById('da-av-months').textContent.trim();const avInterest=document.getElementById('da-av-interest').textContent.trim();const sbMonths=document.getElementById('da-sb-months').textContent.trim();const sbInterest=document.getElementById('da-sb-interest').textContent.trim();let text='My Debt Strategy Comparison (via DebtFreePathways.com)\n';text+='━━━━━━━━━━━━━━━━━━━━━━━━\n';text+='🏔 Avalanche: '+avMonths+' · '+avInterest+' interest\n';text+='❄️ Snowball:  '+sbMonths+' · '+sbInterest+' interest\n';text+='🏆 '+title+'\n';text+='\nShare this result: '+window.location.href;copyResult(text,'da-share-btn');}

function efShareResult(){const goal=document.getElementById('ef-ring-val').textContent.trim();const monthly=document.getElementById('ef-monthly-exp').textContent.trim();const coverage=document.getElementById('ef-coverage-months').textContent.trim();const timeline=document.getElementById('ef-timeline-date').textContent.trim();let text='My Emergency Fund Plan (via DebtFreePathways.com)\n';text+='━━━━━━━━━━━━━━━━━━━━━━━━\n';text+='🎯 Target fund: '+goal+'\n';text+='📊 Monthly expenses: '+monthly+'\n';text+='🛡 Coverage: '+coverage+'\n';if(timeline&&timeline!=='—')text+='📅 Timeline to goal: '+timeline+'\n';text+='\nShare this result: '+window.location.href;copyResult(text,'ef-share-btn');}

function ircShareResult(){const winner=document.getElementById('irc-winner-title').textContent.trim();const saved=document.getElementById('irc-winner-amount').textContent.trim();const diffMonthly=document.getElementById('irc-diff-monthly').textContent.trim();const diffInterest=document.getElementById('irc-diff-interest').textContent.trim();const aName=document.getElementById('irc-th-a').textContent.trim();const bName=document.getElementById('irc-th-b').textContent.trim();let text='My Interest Rate Comparison (via DebtFreePathways.com)\n';text+='━━━━━━━━━━━━━━━━━━━━━━━━\n';text+='🏆 '+winner+'\n';text+='💰 Total savings: '+saved+'\n';text+='📊 Monthly difference: '+diffMonthly+'\n';text+='💸 Interest difference: '+diffInterest+'\n';text+='\nShare this result: '+window.location.href;copyResult(text,'irc-share-btn');}

/* ═══════════════════════════════════════
   URL QUERY STRING — save & restore calculator state
═══════════════════════════════════════ */