function mgSetType(type,btn){document.querySelectorAll('.loan-type-tab').forEach(t=>t.classList.remove('active'));btn.classList.add('active');const configs={fixed30:{rate:6.8,term:30},fixed15:{rate:6.1,term:15},arm5:{rate:6.3,term:30},custom:{rate:null,term:null}};const c=configs[type];if(c.rate!==null){document.getElementById('mg-rate').value=c.rate;document.getElementById('mg-term').value=c.term;}
mgCalc();}
function mgDownChange(){const price=+document.getElementById('mg-price').value||0;const down=+document.getElementById('mg-down').value||0;if(price>0){const pct=(down/price*100).toFixed(1);document.getElementById('mg-down-pct').textContent=pct+'%';}
const pct=price>0?down/price:1;if(pct<0.2&&mgOptionalOn){const loanAmt=price-down;const suggestedPMI=Math.round(loanAmt*0.008/12);document.getElementById('mg-pmi').value=suggestedPMI;}
mgCalc();}
function mgSyncRateSlider(val){document.getElementById('mg-rate').value=val;document.getElementById('mg-rate-slider-val').textContent=parseFloat(val).toFixed(2)+'%';const pct=((val-1)/(15-1))*100;document.getElementById('mg-rate-slider').style.setProperty('--pct',pct+'%');mgCalc();}
function mgSyncSliderFromInput(){const val=+document.getElementById('mg-rate').value||0;const c=Math.min(15,Math.max(1,val));document.getElementById('mg-rate-slider').value=c;document.getElementById('mg-rate-slider-val').textContent=val.toFixed(2)+'%';const pct=((c-1)/(15-1))*100;document.getElementById('mg-rate-slider').style.setProperty('--pct',pct+'%');}
function mgToggleOptional(){mgOptionalOn=!mgOptionalOn;document.getElementById('mg-optional-switch').classList.toggle('on',mgOptionalOn);document.getElementById('mg-optional-row').classList.toggle('show',mgOptionalOn);mgCalc();}
function mgToggleExtra(){mgExtraOn=!mgExtraOn;document.getElementById('mg-extra-switch').classList.toggle('on',mgExtraOn);document.getElementById('mg-extra-row').classList.toggle('show',mgExtraOn);mgCalc();}
function mgMonthlyPayment(principal,annualRate,termMonths){if(annualRate===0)return principal/termMonths;const r=annualRate/100/12;return principal*r*Math.pow(1+r,termMonths)/(Math.pow(1+r,termMonths)-1);}
function mgCalc(){mgSyncSliderFromInput();const price=+document.getElementById('mg-price').value||0;const down=+document.getElementById('mg-down').value||0;const rate=+document.getElementById('mg-rate').value||0;const termYrs=+document.getElementById('mg-term').value||30;const extra=mgExtraOn?(+document.getElementById('mg-extra').value||0):0;const tax=mgOptionalOn?(+document.getElementById('mg-tax').value||0):0;const insurance=mgOptionalOn?(+document.getElementById('mg-insurance').value||0):0;const pmi=mgOptionalOn?(+document.getElementById('mg-pmi').value||0):0;const hoa=mgOptionalOn?(+document.getElementById('mg-hoa').value||0):0;if(price>0){document.getElementById('mg-down-pct').textContent=(down/price*100).toFixed(1)+'%';}
const loanAmt=Math.max(0,price-down);if(!loanAmt||!price){document.getElementById('mg-results-panel').classList.remove('show');return;}
const termMonths=termYrs*12;const piPayment=mgMonthlyPayment(loanAmt,rate,termMonths);const monthlyOther=(tax+insurance)/12+pmi+hoa;const totalMonthly=piPayment+monthlyOther;mgSched=calcAmort(loanAmt,rate,piPayment);mgSchedExtra=extra>0?calcAmort(loanAmt,rate,piPayment+extra):null;if(!mgSched){document.getElementById('mg-results-panel').classList.remove('show');return;}
document.getElementById('mg-results-panel').classList.add('show');const totalInterest=mgSched[mgSched.length-1].totalInterest;const totalPaid=loanAmt+totalInterest;const months=mgSched.length;const prinPct=Math.round((loanAmt/totalPaid)*100);const intPct=100-prinPct;document.getElementById('mg-monthly-pi').textContent=fmt(piPayment);document.getElementById('mg-monthly-total').textContent=monthlyOther>0?fmt(totalMonthly):'—';document.getElementById('mg-total-interest').textContent=fmt(totalInterest);document.getElementById('mg-total-cost').textContent=fmt(totalPaid);document.getElementById('mg-payoff-date').textContent=payoffDate(months);document.getElementById('mg-progress-pct-label').textContent=prinPct+'%';document.getElementById('mg-progress-int-label').textContent=intPct+'%';document.getElementById('mg-progress-bar').style.width=prinPct+'%';const ltv=loanAmt/price;const ltvPct=Math.min(100,Math.round(ltv*100));document.getElementById('mg-ltv-needle').style.left=ltvPct+'%';const ltvStatus=document.getElementById('mg-ltv-status');if(ltv<=0.8){ltvStatus.textContent=`LTV: ${ltvPct}% — Excellent (no PMI required)`;ltvStatus.className='afford-status good';}
else if(ltv<=0.9){ltvStatus.textContent=`LTV: ${ltvPct}% — Good (PMI may apply)`;ltvStatus.className='afford-status ok';}
else{ltvStatus.textContent=`LTV: ${ltvPct}% — High (PMI required, consider larger down payment)`;ltvStatus.className='afford-status high';}
document.getElementById('mg-countdown-widget').style.display='block';document.getElementById('mg-cw-payment').textContent=fmt(piPayment);document.getElementById('mg-cw-payoff').textContent='Payoff: '+payoffDate(months);document.getElementById('mg-rate-compare').style.display='block';document.getElementById('mg-rc-your').textContent=rate.toFixed(2)+'%';const vs30=rate-6.8;document.getElementById('mg-rc-vs').textContent=(vs30>=0?'+':'')+vs30.toFixed(2)+'% vs avg';document.getElementById('mg-rc-vs').style.color=vs30>0?'#ff8585':vs30<0?'#0DBF7E':'rgba(255,255,255,.7)';const mw=document.getElementById('mg-motive-widget');mw.style.display='block';const ir=totalInterest/loanAmt;let msg='';if(ir>1)msg=`Over the life of this loan, you'll pay <strong>${fmt(totalInterest)}</strong> in interest — more than the loan itself. Extra principal payments make a huge difference here.`;else if(ir>0.6)msg=`You're looking at <strong>${fmt(totalInterest)}</strong> total in interest. Even $100/mo extra could save you tens of thousands.`;else msg=`Great rate or term! You'll pay only <strong>${fmt(totalInterest)}</strong> in interest on a ${fmt(loanAmt)} loan.`;document.getElementById('mg-motive-text').innerHTML=msg;const sb=document.getElementById('mg-savings-banner');const cc=document.getElementById('mg-compare-card');if(mgSchedExtra){const intExtra=mgSchedExtra[mgSchedExtra.length-1].totalInterest;const mExtra=mgSchedExtra.length;const saved=totalInterest-intExtra;const mSaved=months-mExtra;const ySaved=Math.floor(mSaved/12);const remSaved=mSaved%12;const timeSave=ySaved>0?(remSaved>0?`${ySaved}y ${remSaved}m earlier`:`${ySaved}y earlier`):`${mSaved}mo earlier`;document.getElementById('mg-savings-val').innerHTML=`${fmt(saved)} &nbsp;·&nbsp; ${timeSave}`;sb.classList.add('show');cc.classList.add('show');document.getElementById('mg-cmp-pay-std').textContent=fmt(piPayment);document.getElementById('mg-cmp-pay-ext').textContent=fmt(piPayment+extra);document.getElementById('mg-cmp-time-std').textContent=fmtM(months);document.getElementById('mg-cmp-time-ext').textContent=fmtM(mExtra);document.getElementById('mg-cmp-time-save').textContent=timeSave;document.getElementById('mg-cmp-int-std').textContent=fmt(totalInterest);document.getElementById('mg-cmp-int-ext').textContent=fmt(intExtra);document.getElementById('mg-cmp-int-save').textContent=fmt(saved);document.getElementById('mg-cmp-total-std').textContent=fmt(totalPaid);document.getElementById('mg-cmp-total-ext').textContent=fmt(loanAmt+intExtra);document.getElementById('mg-cmp-total-save').textContent=fmt(totalPaid-(loanAmt+intExtra));document.getElementById('mg-tl-leg-extra').style.display='flex';}else{sb.classList.remove('show');cc.classList.remove('show');document.getElementById('mg-tl-leg-extra').style.display='none';}
drawMgRing(piPayment,monthlyOther,tax,insurance,pmi,hoa);drawBarChartEl('mg-bar-chart',mgSched);drawTimelineCanvas('mg-balance-canvas',mgSched,mgSchedExtra);document.getElementById('mg-table-card').classList.add('show');if(mgTableVisible)mgBuildTable();}
function drawMgRing(pi,other,tax,insurance,pmi,hoa){const total=pi+other;const svg=document.getElementById('mg-ring-svg');document.getElementById('mg-ring-center').textContent=fmt(total);const segments=[];segments.push({label:'Principal & Interest',val:pi,color:'#1A6FE8'});if(tax>0)segments.push({label:'Property tax',val:tax/12,color:'#F5A623'});if(insurance>0)segments.push({label:'Insurance',val:insurance/12,color:'#7C3AED'});if(pmi>0)segments.push({label:'PMI',val:pmi,color:'#E84040'});if(hoa>0)segments.push({label:'HOA',val:hoa,color:'#0DBF7E'});const cx=80,cy=80,r=62,sw=22;const toRad=d=>(d-90)*Math.PI/180;let html=`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#EFF1F7" stroke-width="${sw}"/>`;let startAngle=0;const gap=3;segments.forEach((seg,i)=>{const angle=(seg.val/total)*360;const s=startAngle+gap/2,e=startAngle+angle-gap/2;if(e>s){const x1=cx+r*Math.cos(toRad(s)),y1=cy+r*Math.sin(toRad(s));const x2=cx+r*Math.cos(toRad(e)),y2=cy+r*Math.sin(toRad(e));const lg=e-s>180?1:0;html+=`<path d="M${x1} ${y1} A${r} ${r} 0 ${lg} 1 ${x2} ${y2}" fill="none" stroke="${seg.color}" stroke-width="${sw}" stroke-linecap="round"/>`;}
startAngle+=angle;});svg.innerHTML=html;const legend=document.getElementById('mg-ring-legend');legend.innerHTML=segments.map(seg=>{const pct=Math.round((seg.val/total)*100);return`<div class="ring-leg-item"><div class="ring-leg-left"><div class="ring-leg-dot" style="background:${seg.color}"></div><div class="ring-leg-name">${seg.label}</div></div><div style="text-align:right"><div class="ring-leg-val">${fmt(seg.val)}/mo</div><div class="ring-leg-pct">${pct}%</div></div></div>`;}).join('');}
function mgSwitchTab(tab){mgActiveTab=tab;const tabs=['breakdown','bar','balance'];document.querySelectorAll('#page-mortgage .chart-tab').forEach((t,i)=>t.classList.toggle('active',tabs[i]===tab));document.querySelectorAll('#page-mortgage .chart-panel').forEach((p,i)=>p.classList.toggle('active',['mg-tab-breakdown','mg-tab-bar','mg-tab-balance'][i]==='mg-tab-'+tab));if(tab==='balance'&&mgSched)drawTimelineCanvas('mg-balance-canvas',mgSched,mgSchedExtra);}
function mgSwitchTableView(v){mgTableViewMode=v;document.getElementById('mg-view-monthly').classList.toggle('active',v==='monthly');document.getElementById('mg-view-yearly').classList.toggle('active',v==='yearly');if(mgTableVisible)mgBuildTable();}
function mgToggleTable(){mgTableVisible=!mgTableVisible;document.getElementById('mg-table-scroll').style.display=mgTableVisible?'block':'none';document.getElementById('mg-table-toggle-btn').textContent=mgTableVisible?'Hide ↑':'Show ↓';if(mgTableVisible)mgBuildTable();}
function mgBuildTable(){if(!mgSched)return;const tbody=document.getElementById('mg-amort-body');tbody.innerHTML='';const loanAmt=Math.max(0,(+document.getElementById('mg-price').value||0)-(+document.getElementById('mg-down').value||0));if(mgTableViewMode==='monthly'){let lastYr=0;mgSched.forEach(row=>{const yr=Math.ceil(row.month/12);if(yr!==lastYr){const yrow=document.createElement('tr');yrow.className='yr-header';yrow.innerHTML=`<td colspan="6">Year ${yr}</td>`;tbody.appendChild(yrow);lastYr=yr;}
const equity=loanAmt-row.balance;const tr=document.createElement('tr');tr.innerHTML=`<td class="muted">${row.month}</td><td>${fmt(row.payment)}</td><td class="col-principal">${fmt(row.principal)}</td><td class="col-interest">${fmt(row.interest)}</td><td class="col-balance">${fmt(row.balance)}</td><td class="col-principal">${fmt(equity)}</td>`;tbody.appendChild(tr);});}else{const years={};mgSched.forEach(row=>{const yr=Math.ceil(row.month/12);if(!years[yr])years[yr]={totalPay:0,totalPrin:0,totalInt:0,endBal:0};years[yr].totalPay+=row.payment;years[yr].totalPrin+=row.principal;years[yr].totalInt+=row.interest;years[yr].endBal=row.balance;});Object.keys(years).forEach(yr=>{const d=years[yr];const equity=loanAmt-d.endBal;const tr=document.createElement('tr');tr.className='yr-summary';tr.innerHTML=`<td class="yr-label">Year ${yr}</td><td>${fmt(d.totalPay)}</td><td class="col-principal">${fmt(d.totalPrin)}</td><td class="col-interest">${fmt(d.totalInt)}</td><td class="col-balance">${fmt(d.endBal)}</td><td class="col-principal">${fmt(equity)}</td>`;tbody.appendChild(tr);});}}
let laSched=null,laSchedExtra=null,laTableVisible=false,laTableViewMode='monthly',laExtraOn=false,laActiveTab='breakdown';(function(){const el=document.getElementById('la-start');if(el){const now=new Date();el.value=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');}})();const laPresets={personal:{amount:25000,term:'60',rate:9.5,hint:'Avg. personal loan amount'},auto:{amount:35000,term:'60',rate:7.0,hint:'New car loan amount'},student:{amount:30000,term:'120',rate:5.5,hint:'Federal student loan balance'},mortgage:{amount:350000,term:'360',rate:6.8,hint:'Home loan principal'},business:{amount:50000,term:'60',rate:8.5,hint:'Small business loan'}};