function daUpdateRemoveButtons(){const btns=document.querySelectorAll('.da-remove-btn');const single=btns.length===1;btns.forEach(b=>{b.disabled=single;});}
function daAddRow(){const list=document.getElementById('da-debt-list');const row=document.createElement('div');row.className='da-debt-row';row.innerHTML=`
    <div class="input-group"><label>Debt name</label><div class="input-wrap"><input type="text" class="da-name" value="New Debt" oninput="daCalc()"></div></div>
    <div class="input-group"><label>Balance ($)</label><div class="input-wrap has-prefix"><span class="input-prefix">$</span><input type="number" class="da-balance" value="5000" min="0" oninput="daCalc()"></div></div>
    <div class="input-group"><label>Interest rate (%)</label><div class="input-wrap has-suffix"><input type="number" class="da-rate" value="10" step="0.1" min="0" oninput="daCalc()"><span class="input-suffix">%</span></div></div>
    <div class="input-group"><label>Min. payment ($)</label><div class="input-wrap has-prefix"><span class="input-prefix">$</span><input type="number" class="da-minpay" value="100" min="0" oninput="daCalc()"></div></div>
    <button class="da-remove-btn" onclick="daRemoveRow(this)" title="Remove">×</button>`;list.appendChild(row);daUpdateRemoveButtons();daCalc();}
function daRemoveRow(btn){const rows=document.querySelectorAll('.da-debt-row');if(rows.length<=1)return;btn.closest('.da-debt-row').remove();daUpdateRemoveButtons();daCalc();}
function daGetDebts(){return Array.from(document.querySelectorAll('.da-debt-row')).map(r=>({name:r.querySelector('.da-name').value||'Debt',balance:parseFloat(r.querySelector('.da-balance').value)||0,rate:parseFloat(r.querySelector('.da-rate').value)||0,minPay:parseFloat(r.querySelector('.da-minpay').value)||0})).filter(d=>d.balance>0);}
function daSimulate(debts,budget,trackCumInt){let ds=debts.map(d=>({...d}));let totalInterest=0,cumInt=0,month=0;const balanceSnaps=[],cumIntSnaps=[];while(ds.some(d=>d.balance>0.005)&&month<600){month++;let remaining=budget;ds.forEach(d=>{if(d.balance<=0)return;const intChg=d.balance*(d.rate/100/12);totalInterest+=intChg;cumInt+=intChg;d.balance+=intChg;const pay=Math.min(d.minPay,d.balance);d.balance=Math.max(0,d.balance-pay);remaining-=pay;});const target=ds.find(d=>d.balance>0);if(target&&remaining>0)target.balance=Math.max(0,target.balance-Math.min(remaining,target.balance));ds.forEach(d=>{if(d.balance<=0&&!d.months)d.months=month;});balanceSnaps.push(ds.reduce((s,d)=>s+d.balance,0));cumIntSnaps.push(cumInt);}
ds.forEach(d=>{if(!d.months)d.months=month;});return{months:month,totalInterest,debts:ds,balanceSnaps,cumIntSnaps};}
function daCalc(){daUpdateRemoveButtons();const debts=daGetDebts();const panel=document.getElementById('da-results-panel');const errEl=document.getElementById('da-budget-error');const minTotalEl=document.getElementById('da-min-total');if(!debts.length){panel.classList.remove('show');return;}
const budget=parseFloat(document.getElementById('da-budget').value)||0;const totalMin=debts.reduce((s,d)=>s+d.minPay,0);const totalBal=debts.reduce((s,d)=>s+d.balance,0);if(budget<totalMin){panel.classList.remove('show');errEl.style.display='block';minTotalEl.textContent=fmt(totalMin);return;}
errEl.style.display='none';const avDebts=[...debts].sort((a,b)=>b.rate-a.rate);const sbDebts=[...debts].sort((a,b)=>a.balance-b.balance);const avResult=daSimulate(avDebts,budget);const sbResult=daSimulate(sbDebts,budget);const avTotal=totalBal+avResult.totalInterest;const sbTotal=totalBal+sbResult.totalInterest;const intDiff=Math.abs(sbResult.totalInterest-avResult.totalInterest);const monthsDiff=Math.abs(sbResult.months-avResult.months);const avWins=avResult.totalInterest<=sbResult.totalInterest;panel.classList.add('show');document.getElementById('da-savings-title').textContent=avWins?'Avalanche saves you more money':'Snowball pays off faster';document.getElementById('da-savings-sub').textContent=avWins?`Save ${fmt(intDiff)} in interest vs Snowball`:`${monthsDiff} month${monthsDiff !== 1 ? 's' : ''} faster than Avalanche`;document.getElementById('da-savings-amount').textContent=avWins?fmt(intDiff):fmtM(monthsDiff);document.getElementById('da-av-months').textContent=fmtM(avResult.months);document.getElementById('da-av-interest').textContent=fmt(avResult.totalInterest);document.getElementById('da-av-total').textContent=fmt(avTotal);document.getElementById('da-av-winner').style.display=avWins?'inline-flex':'none';document.getElementById('da-sb-months').textContent=fmtM(sbResult.months);document.getElementById('da-sb-interest').textContent=fmt(sbResult.totalInterest);document.getElementById('da-sb-total').textContent=fmt(sbTotal);document.getElementById('da-sb-winner').style.display=!avWins?'inline-flex':'none';function renderOrder(elId,sortedDebts,result){document.getElementById(elId).innerHTML=sortedDebts.map((d,i)=>{const found=result.debts.find(x=>x.name===d.name);return`<div class="da-debt-item">
        <div class="da-debt-num">${i + 1}</div>
        <div class="da-debt-item-name">${d.name}</div>
        <div class="da-debt-item-meta">${fmtM(found?.months || 0)}</div>
      </div>`;}).join('');}
renderOrder('da-av-order',avDebts,avResult);renderOrder('da-sb-order',sbDebts,sbResult);document.getElementById('da-strategy-widget').style.display='block';document.getElementById('da-motive-widget').style.display='block';document.getElementById('da-sw-count').textContent=debts.length;document.getElementById('da-sw-balance').textContent=fmt(totalBal);document.getElementById('da-sw-budget').textContent=fmt(budget);document.getElementById('da-sw-extra').textContent=fmt(budget-totalMin);document.getElementById('da-motive-text').textContent=avWins?`Avalanche saves you ${fmt(intDiff)} in interest. Snowball can keep you motivated with quicker wins.`:`Both methods are very close. Snowball is faster — and the motivation boost may be worth the small extra cost.`;daDrawTwoLine('da-balance-canvas',avResult.balanceSnaps,sbResult.balanceSnaps,'#7C3AED','#0DBF7E');daDrawTwoLine('da-interest-canvas',avResult.cumIntSnaps,sbResult.cumIntSnaps,'#7C3AED','#0DBF7E');}
function daDrawTwoLine(canvasId,seriesA,seriesB,colorA,colorB){const canvas=document.getElementById(canvasId);if(!canvas)return;const dpr=window.devicePixelRatio||1;const W=canvas.parentElement.offsetWidth||600;const H=200;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.clearRect(0,0,W,H);const maxLen=Math.max(seriesA.length,seriesB.length);const maxVal=Math.max(...seriesA,...seriesB,1);const pad={t:10,r:16,b:28,l:52};const cW=W-pad.l-pad.r,cH=H-pad.t-pad.b;ctx.strokeStyle='#EFF1F7';ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=pad.t+cH-(i/4)*cH;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(pad.l+cW,y);ctx.stroke();ctx.fillStyle='#9CA3AF';ctx.font='10px sans-serif';ctx.textAlign='right';ctx.fillText('$'+Math.round(maxVal*i/4).toLocaleString(),pad.l-4,y+4);}
function drawLine(series,color){if(!series.length)return;ctx.strokeStyle=color;ctx.lineWidth=2.5;ctx.lineJoin='round';ctx.beginPath();series.forEach((v,i)=>{const x=pad.l+(i/(maxLen-1||1))*cW;const y=pad.t+cH-(v/maxVal)*cH;i===0?ctx.moveTo(x,y):ctx.lineTo(x,y);});ctx.stroke();}
drawLine(seriesA,colorA);drawLine(seriesB,colorB);ctx.fillStyle='#9CA3AF';ctx.font='10px sans-serif';ctx.textAlign='center';for(let i=0;i<=4;i++){const m=Math.round((i/4)*(maxLen-1));ctx.fillText(fmtM(m),pad.l+(i/4)*cW,H-4);}}
function daSwitchTab(tab){document.querySelectorAll('#page-debt-avalanche .chart-tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===tab));document.querySelectorAll('#page-debt-avalanche .chart-panel').forEach(p=>p.classList.toggle('active',p.id==='da-tab-'+tab));daCalc();}
let daResizeTimer;window.addEventListener('resize',()=>{clearTimeout(daResizeTimer);daResizeTimer=setTimeout(()=>{const panel=document.getElementById('da-results-panel');if(panel&&panel.classList.contains('show')){const activeTab=document.querySelector('#page-debt-avalanche .chart-panel.active');if(activeTab){const canvasId=activeTab.querySelector('canvas')?.id;if(canvasId){daCalc();}}}},200);});let efTargetMonths=3;let efExistingOn=false;